version: '3'

services:
  node:
    build: .
    environment:
      - ENV=docker
    volumes:
      - ../app/data:/app/data
      - ../app:/app/
    command: python app.py

  node1:
    extends:
      service: node
    env_file:
      - node1.env
    ports:
      - "5001:5001"

  node2:
    extends:
      service: node
    env_file:
      - node2.env
    ports:
      - "5002:5002"

  node3:
    extends:
      service: node
    env_file:
      - node3.env
    ports:
      - "5003:5003"
